### ISSUE TITLE
App crashes when printing

### ISSUE THREAD

**Issue by bplogan** [katzer/cordova-plugin-printer#140]
I started a new Ionic 2 app and have one page with the print function on it. The html I am printing is <b>Test</b>. When try to print the app crashes "unfortunately the app has stopped". I've tried with the latest version and previous version of the package.  It does get past the Printer.isAvailable() then crashes on the Printer.Print(html);

`printTest(){
    if(Printer.isAvailable()){
      Printer.print(html);
    }
  }`

Any help would we appreciated :)

**Comment by bplogan** [comment]
Here is the stack trace:
  at de.appplant.cordova.plugin.printer.Printer.setWebViewClient(Printer.java:245)
  at de.appplant.cordova.plugin.printer.Printer.initWebView(Printer.java:235)
  at de.appplant.cordova.plugin.printer.Printer.access$300(Printer.java:62)
  at de.appplant.cordova.plugin.printer.Printer$3.run(Printer.java:174)
  at android.os.Handler.handleCallback(Handler.java:751)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:154)
  at android.app.ActivityThread.main(ActivityThread.java:6682)
  at java.lang.reflect.Method.invoke(Native Method:0)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by bplogan** [comment]
I managed to get past this, it was my configuration being out of date.  I updated everything to latest and can now print.  Thanks.

![image](https://user-images.githubusercontent.com/8459106/27595897-579b3c44-5b34-11e7-912f-f8f574ba4d30.png)
