### ISSUE TITLE
Plugin crashes when closing app in background on Android

### ISSUE THREAD

**Issue by adamfellon** [katzer/cordova-plugin-printer#144]
On android if the app is closed in the background ([ ] -> X) the app crashes.

Here is the stack trace noting the printer plugin's exception:
```
A/art: art/runtime/entrypoints/entrypoint_utils.cc:219] Check failed: throws_index < static_cast<int>(num_virtuals) (throws_index=49262703, static_cast<int>(num_virtuals)=4) 
A/art: art/runtime/runtime.cc:403] Runtime aborting...
A/art: art/runtime/runtime.cc:403] Aborting thread:
A/art: art/runtime/runtime.cc:403] "main" prio=7 tid=1 Runnable
A/art: art/runtime/runtime.cc:403]   | group="" sCount=0 dsCount=0 obj=0x753076f0 self=0xb058b400
A/art: art/runtime/runtime.cc:403]   | sysTid=2722 nice=-4 cgrp=default sched=0/0 handle=0xb48a3534
A/art: art/runtime/runtime.cc:403]   | state=R schedstat=( 0 0 0 ) utm=140 stm=115 core=1 HZ=100
A/art: art/runtime/runtime.cc:403]   | stack=0xbf123000-0xbf125000 stackSize=8MB
A/art: art/runtime/runtime.cc:403]   | held mutexes= "abort lock" "mutator lock"(shared held)
A/art: art/runtime/runtime.cc:403]   native: #00 pc 0056d8de  /system/lib/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiP12BacktraceMapPKcPNS_9ArtMethodEPv+238)
A/art: art/runtime/runtime.cc:403]   native: #01 pc 00539f6e  /system/lib/libart.so (_ZNK3art6Thread9DumpStackERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEbP12BacktraceMap+526)
A/art: art/runtime/runtime.cc:403]   native: #02 pc 00536f6b  /system/lib/libart.so (_ZNK3art6Thread4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEbP12BacktraceMap+75)
A/art: art/runtime/runtime.cc:403]   native: #03 pc 00522d43  /system/lib/libart.so (_ZNK3art10AbortState10DumpThreadERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEPNS_6ThreadE+67)
A/art: art/runtime/runtime.cc:403]   native: #04 pc 005229fa  /system/lib/libart.so (_ZNK3art10AbortState4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+330)
A/art: art/runtime/runtime.cc:403]   native: #05 pc 0051327b  /system/lib/libart.so (_ZN3art7Runtime5AbortEv+155)
A/art: art/runtime/runtime.cc:403]   native: #06 pc 00119572  /system/lib/libart.so (_ZN3art10LogMessageD1Ev+1298)
A/art: art/runtime/runtime.cc:403]   native: #07 pc 005bae87  /system/lib/libart.so (_ZN3art28InvokeProxyInvocationHandlerERNS_33ScopedObjectAccessAlreadyRunnableEPKcP8_jobjectS5_RNSt3__16vectorI6jvalueNS6_9allocatorIS8_EEEE+3175)
A/art: art/runtime/runtime.cc:403]   native: #08 pc 00668b30  /system/lib/libart.so (artQuickProxyInvokeHandler+1520)
A/art: art/runtime/runtime.cc:403]   native: #09 pc 0010e206  /system/lib/libart.so (art_quick_proxy_invoke_handler+54)
A/art: art/runtime/runtime.cc:403]   native: #10 pc 009e5235  /system/framework/x86/boot-framework.oat (???)
A/art: art/runtime/runtime.cc:403]   at java.lang.Object.equals(Object.java:160)
A/art: art/runtime/runtime.cc:403]   at android.util.ArrayMap.indexOf(ArrayMap.java:105)
A/art: art/runtime/runtime.cc:403]   at android.util.ArrayMap.indexOfKey(ArrayMap.java:343)
A/art: art/runtime/runtime.cc:403]   at android.util.ArrayMap.remove(ArrayMap.java:582)
A/art: art/runtime/runtime.cc:403]   at android.print.PrintManager.removePrintJobStateChangeListener(PrintManager.java:356)
A/art: art/runtime/runtime.cc:403]   at java.lang.reflect.Method.invoke!(Native method)
A/art: art/runtime/runtime.cc:403]   at de.appplant.cordova.plugin.printer.reflect.Meta.invokeMethod(Meta.java:87)
A/art: art/runtime/runtime.cc:403]   at de.appplant.cordova.plugin.printer.ext.PrintManager.unsetOnPrintJobStateChangeListener(PrintManager.java:213)
A/art: art/runtime/runtime.cc:403]   at de.appplant.cordova.plugin.printer.Printer.onDestroy(Printer.java:346)
A/art: art/runtime/runtime.cc:403]   at org.apache.cordova.PluginManager.onDestroy(PluginManager.java:297)
A/art: art/runtime/runtime.cc:403]   at org.apache.cordova.CordovaWebViewImpl.handleDestroy(CordovaWebViewImpl.java:480)
A/art: art/runtime/runtime.cc:403]   at org.apache.cordova.CordovaActivity.onDestroy(CordovaActivity.java:315)
A/art: art/runtime/runtime.cc:403]   at android.app.Activity.performDestroy(Activity.java:6866)
A/art: art/runtime/runtime.cc:403]   at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1153)
A/art: art/runtime/runtime.cc:403]   at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4154)
A/art: art/runtime/runtime.cc:403]   at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4185)
A/art: art/runtime/runtime.cc:403]   at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4459)
A/art: art/runtime/runtime.cc:403]   at android.app.ActivityThread.-wrap19(ActivityThread.java:-1)
A/art: art/runtime/runtime.cc:403]   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1466)
A/art: art/runtime/runtime.cc:403]   at android.os.Handler.dispatchMessage(Handler.java:102)
A/art: art/runtime/runtime.cc:403]   at android.os.Looper.loop(Looper.java:154)
A/art: art/runtime/runtime.cc:403]   at android.app.ActivityThread.main(ActivityThread.java:6077)
A/art: art/runtime/runtime.cc:403]   at java.lang.reflect.Method.invoke!(Native method)
A/art: art/runtime/runtime.cc:403]   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
A/art: art/runtime/runtime.cc:403]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
A/art: art/runtime/runtime.cc:403] Pending exception java.lang.Exception: 
A/art: art/runtime/runtime.cc:403]   at java.lang.Object de.appplant.cordova.plugin.printer.ext.PrintManager$OnPrintJobStateChangeProxy.invoke(java.lang.Object, java.lang.reflect.Method, java.lang.Object[]) (PrintManager.java:66)
A/art: art/runtime/runtime.cc:403]   at java.lang.Object java.lang.reflect.Proxy.invoke(java.lang.reflect.Proxy, java.lang.reflect.Method, java.lang.Object[]) (Proxy.java:813)
A/art: art/runtime/runtime.cc:403]   at boolean java.lang.Object.equals(java.lang.Object) ((null):-1)
A/art: art/runtime/runtime.cc:403]   at int android.util.ArrayMap.indexOf(java.lang.Object, int) (ArrayMap.java:105)
A/art: art/runtime/runtime.cc:403]   at int android.util.ArrayMap.indexOfKey(java.lang.Object) (ArrayMap.java:343)
A/art: art/runtime/runtime.cc:403]   at java.lang.Object android.util.ArrayMap.remove(java.lang.Object) (ArrayMap.java:582)
A/art: art/runtime/runtime.cc:403]   at void android.print.PrintManager.removePrintJobStateChangeListener(android.print.PrintManager$PrintJobStateChangeListener) (PrintManager.java:356)
A/art: art/runtime/runtime.cc:403]   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
A/art: art/runtime/runtime.cc:403]   at java.lang.Object de.appplant.cordova.plugin.printer.reflect.Meta.invokeMethod(java.lang.Object, java.lang.reflect.Method, java.lang.Object[]) (Meta.java:87)
A/art: art/runtime/runtime.cc:403]   at void de.appplant.cordova.plugin.printer.ext.PrintManager.unsetOnPrintJobStateChangeListener() (PrintManager.java:213)
A/art: art/runtime/runtime.cc:403]   at void de.appplant.cordova.plugin.printer.Printer.onDestroy() (Printer.java:346)
A/art: art/runtime/runtime.cc:403]   at void org.apache.cordova.PluginManager.onDestroy() (PluginManager.java:297)
A/art: art/runtime/runtime.cc:403]   at void org.apache.cordova.CordovaWebViewImpl.handleDestroy() (CordovaWebViewImpl.java:480)
A/art: art/runtime/runtime.cc:403]   at void org.apache.cordova.CordovaActivity.onDestroy() (CordovaActivity.java:315)
A/art: art/runtime/runtime.cc:403]   at void android.app.Activity.performDestroy() (Activity.java:6866)
A/art: art/runtime/runtime.cc:403]   at void android.app.Instrumentation.callActivityOnDestroy(android.app.Activity) (Instrumentation.java:1153)
A/art: art/runtime/runtime.cc:403]   at android.app.ActivityThread$ActivityClientRecord android.app.ActivityThread.performDestroyActivity(android.os.IBinder, boolean, int, boolean) (ActivityThread.java:4154)
A/art: art/runtime/runtime.cc:403]   at void android.app.ActivityThread.handleDestroyActivity(android.os.IBinder, boolean, int, boolean) (ActivityThread.java:4185)
A/art: art/runtime/runtime.cc:403]   at void android.app.ActivityThread.handleRelaunchActivity(android.app.ActivityThread$ActivityClientRecord) (ActivityThread.java:4459)
A/art: art/runtime/runtime.cc:403]   at void android.app.ActivityThread.-wrap19(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord) (ActivityThread.java:-1)
A/art: art/runtime/runtime.cc:403]   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1466)
A/art: art/runtime/runtime.cc:403]   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
A/art: art/runtime/runtime.cc:403]   at void android.os.Looper.loop() (Looper.java:154)
A/art: art/runtime/runtime.cc:403]   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6077)
A/art: art/runtime/runtime.cc:403]   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
A/art: art/runtime/runtime.cc:403]   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:865)
A/art: art/runtime/runtime.cc:403]   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:755)
```

**Comment by adamfellon** [comment]
Sorry to just bump this, but any idea why art is throwing on the ```unsetOnPrintJobStateChangeListener``` call?

Thanks!

**Comment by cyptus** [comment]
i got the same issue - any news?

**Comment by katzer** [comment]
Should be fixed with upcoming release as these listeners have been removed.
