### ISSUE TITLE
getEnabledPrintServices broken on Android with missing permission READ_PRINT_SERVICES

### ISSUE THREAD

**Issue by paulklinkenberg** [katzer/cordova-plugin-printer#194]
In my app, when tested on an Android 8.1 device, the functionality "cordova.plugins.printer.check" does not work. In logcat, I see the following stacktrace:

`W/System.err: java.lang.reflect.InvocationTargetException
     at java.lang.reflect.Method.invoke(Native Method)
        at de.appplant.cordova.plugin.printer.reflect.Meta.invokeMethod(Meta.java:87)
     at de.appplant.cordova.plugin.printer.ext.PrintManager.getEnabledPrintServices(PrintManager.java:152)
        at de.appplant.cordova.plugin.printer.Printer$2.run(Printer.java:146)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
    at java.lang.Thread.run(Thread.java:764)
    Caused by: java.lang.SecurityException: Neither user 10092 nor current process has android.permission.READ_PRINT_SERVICES.
        at android.os.Parcel.readException(Parcel.java:2005)
        at android.os.Parcel.readException(Parcel.java:1951)
        at android.print.IPrintManager$Stub$Proxy.getPrintServices(IPrintManager.java:621)
     at android.print.PrintManager.getPrintServices(PrintManager.java:639)
    	... 7 more`

Now this tells me that the plugin needs a (new?) permission "READ_PRINT_SERVICES". So I added the permission to the plugin's plugin.xml, but it does not help?!

`<plugin id="cordova-plugin-printer"        xmlns="http://apache.org/cordova/ns/plugins/1.0"        xmlns:android="http://schemas.android.com/apk/res/android"
        version="0.7.4-dev">
      [...]
    <platform name="android">
		<config-file target="AndroidManifest.xml" parent="/*">
			<uses-permission android:name="android.permission.READ_PRINT_SERVICES"/>
		</config-file>
                 [....]`

Do you know what can be done to fix this issue?

**Comment by katzer** [comment]
I've removed all these code and reorganises how it works on Android. Closing it. Wait for the upcoming release.
