### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by mzealey** [katzer/cordova-plugin-printer#206]
Upgraded to 0.8.0 and build is failing on cordova-android 7. Looks due to ANDROID_SUPPORT_V4_VERSION being 28+ ... cordova-android 8 works without issue.

```
:app:processDebugResources/home/mark/.gradle/caches/transforms-1/files-1.1/support-compat-28.0.0.aar/7557fff2f0eb23fb00d4bef9f7834992/res/values/values.xml:133:5-70: AAPT: error: resource android:attr/fontVariationSettings not found.
    
/home/mark/.gradle/caches/transforms-1/files-1.1/support-compat-28.0.0.aar/7557fff2f0eb23fb00d4bef9f7834992/res/values/values.xml:133:5-70: AAPT: error: resource android:attr/ttcIndex not found.
    
phonegap/platforms/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:88: error: resource android:attr/fontVariationSettings not found.
phonegap/platforms/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:88: error: resource android:attr/ttcIndex not found.
error: failed linking references.
```

**Comment by katzer** [comment]
I've used cordova-android@7 and cordova-android@8 without having issues.

**Comment by katzer** [comment]
Its possible to define the support-lib version per app:
https://github.com/katzer/cordova-plugin-printer/blob/master/plugin.xml#L97

**Comment by sambegin** [comment]
I get the same error from a fresh new install :

```
/Users/sambegin/app/platforms/android/gradlew: Command failed with exit code 1 Error output:
/Users/sambegin/.gradle/caches/transforms-1/files-1.1/support-compat-28.0.0.aar/635b345120bb7a183674d7e4721cfbe7/res/values/values.xml: AAPT: error: resource android:attr/fontVariationSettings not found.

/Users/sambegin/.gradle/caches/transforms-1/files-1.1/support-compat-28.0.0.aar/635b345120bb7a183674d7e4721cfbe7/res/values/values.xml: AAPT: error: resource android:attr/ttcIndex not found.

/Users/sambegin/app/platforms/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:87: error: resource android:attr/fontVariationSettings not found.
/Users/sambegin/app/platforms/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:87: error: resource android:attr/ttcIndex not found.
error: failed linking references.

Failed to execute aapt
com.android.ide.common.process.ProcessException: Failed to execute aapt
at com.android.builder.core.AndroidBuilder.processResources(AndroidBuilder.java:796)
at com.android.build.gradle.tasks.ProcessAndroidResources.invokeAaptForSplit(ProcessAndroidResources.java:551)
at com.android.build.gradle.tasks.ProcessAndroidResources.doFullTaskAction(ProcessAndroidResources.java:285)
at com.android.build.gradle.internal.tasks.IncrementalTask.taskAction(IncrementalTask.java:109)
at sun.reflect.GeneratedMethodAccessor332.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:173)
at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
...
```

Using cordova-android 7.1.1

**Comment by biaggi** [comment]
This solution seems to be working for me:

https://forum.ionicframework.com/t/build-break-with-aapt-error-message-why/123955/6

>
>  edited file “project.properties”
> 
> Search for cordova.system.library.2=com.android.support:support-v4:+ and replace for cordova.system.library.2=com.android.support:support-v4:27.1.0.

**Comment by jsitu** [comment]
I ran into the same issue, any updates?

**Comment by coolara** [comment]
> Upgraded to 0.8.0 and build is failing on cordova-android 7. Looks due to ANDROID_SUPPORT_V4_VERSION being 28+ ... cordova-android 8 works without issue.
> 
> ```
> :app:processDebugResources/home/mark/.gradle/caches/transforms-1/files-1.1/support-compat-28.0.0.aar/7557fff2f0eb23fb00d4bef9f7834992/res/values/values.xml:133:5-70: AAPT: error: resource android:attr/fontVariationSettings not found.
>     
> /home/mark/.gradle/caches/transforms-1/files-1.1/support-compat-28.0.0.aar/7557fff2f0eb23fb00d4bef9f7834992/res/values/values.xml:133:5-70: AAPT: error: resource android:attr/ttcIndex not found.
>     
> phonegap/platforms/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:88: error: resource android:attr/fontVariationSettings not found.
> phonegap/platforms/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:88: error: resource android:attr/ttcIndex not found.
> error: failed linking references.
> ```

update cordova-android to 8 safe me
